// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-oPWEXKHl7L_PzouEHyOu6buj_tsbCxM',
    appId: '1:742496189709:web:5969f9cdf093536e9ec444',
    messagingSenderId: '742496189709',
    projectId: 'gift-store-4df43',
    authDomain: 'gift-store-4df43.firebaseapp.com',
    storageBucket: 'gift-store-4df43.firebasestorage.app',
    measurementId: 'G-CL8S19RVC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ShaoIGR3dCQBU4pMRqSYhu36qhpEZeg',
    appId: '1:742496189709:android:1e483152f54287079ec444',
    messagingSenderId: '742496189709',
    projectId: 'gift-store-4df43',
    storageBucket: 'gift-store-4df43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbqRZ0PB8mR62OEe2yy1EFgzZBecGOJ0o',
    appId: '1:742496189709:ios:f939b23a4d9aa9eb9ec444',
    messagingSenderId: '742496189709',
    projectId: 'gift-store-4df43',
    storageBucket: 'gift-store-4df43.firebasestorage.app',
    iosBundleId: 'com.example.giftsStore',
  );
}
